### ISSUE TITLE
ftf-find-file hangs on non-git directories with lots of files

### ISSUE THREAD

**Issue by akalin** [eglaysher/find-things-fast#14]
Unsurprising, but there's probably a way to avoid that. Looking at the documentation for grep, it seems that it can be done asynchronously perhaps?

**Comment by akalin** [comment]
Looked into this a bit, but it seems that doing stuff asynchronously is hard. I'm okay with just hitting C-g whenever I accidentally do ftf-find-file outside of a git dir.

**Comment by eglaysher** [comment]
You're right that it's hard; hopefully concurrency will get easier in emacs in the future.
